/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_jnidemo_NdkJniUtils */

#ifndef _Included_com_edu_jnidemo_NdkJniUtils
#define _Included_com_edu_jnidemo_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_jnidemo_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_edu_jnidemo_NdkJniUtils_getCLanguageString
        (JNIEnv *env, jclass jobj){

    //返回一句话
    return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");

};

#ifdef __cplusplus
}
#endif
#endif
