/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_counternativedemo_CounterNative */

#ifndef _Included_com_edu_counternativedemo_CounterNative
#define _Included_com_edu_counternativedemo_CounterNative
#ifdef __cplusplus
extern "C" {
#endif
jclass m_class;
jobject m_object;
jmethodID m_mid_static,m_mid;
/*
 * Class:     com_edu_counternativedemo_CounterNative
 * Method:    nativeSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_edu_counternativedemo_CounterNative_nativeSetup
  (JNIEnv *env, jobject thiz){
    //*env请求虚拟机,this 的ObjectClass是啥
    jclass clazz = (*env)->GetObjectClass(env,thiz);
    m_class = (jclass)(*env)->NewGlobalRef(env,clazz);
    m_object = (jobject)(*env)->NewGlobalRef(env,thiz);
    m_mid_static = (*env)->GetStaticMethodID(env,m_class,"setValue","(I)V");
//这个class的setV的id是啥

    m_mid = (*env)->GetMethodID(env,m_class,"setV","(I)V");
    return;
  }

/*
 * Class:     com_edu_counternativedemo_CounterNative
 * Method:    nativeExec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_edu_counternativedemo_CounterNative_nativeExec
  (JNIEnv *env, jobject thiz , jint number){
    int i,sum = 0;
      for(i=0;i<=number;i++) sum+=i;
//局域methodId,和this来调用setV
        (*env)->CallVoidMethod(env,m_object,m_mid,sum);
        return;
  }

/*
 * Class:     com_edu_counternativedemo_CounterNative
 * Method:    nativeExecute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_edu_counternativedemo_CounterNative_nativeExecute
  (JNIEnv *env, jclass clazz, jint number){
    int i,sum = 0;
    for(i=0;i<=number;i++) sum+=i;
    (*env)->CallStaticVoidMethod(env,m_class,m_mid_static,sum);
    return;

  }

#ifdef __cplusplus
}
#endif
#endif
