/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_counternativedemo_CounterNative */

#ifndef _Included_com_edu_counternativedemo_CounterNative
#define _Included_com_edu_counternativedemo_CounterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_counternativedemo_CounterNative
 * Method:    nativeSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_edu_counternativedemo_CounterNative_nativeSetup
  (JNIEnv *, jobject);

/*
 * Class:     com_edu_counternativedemo_CounterNative
 * Method:    nativeExec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_edu_counternativedemo_CounterNative_nativeExec
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_edu_counternativedemo_CounterNative
 * Method:    nativeExecute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_edu_counternativedemo_CounterNative_nativeExecute
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
