/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_ndkdemo_HelloNdk */

#ifndef _Included_com_edu_ndkdemo_HelloNdk
#define _Included_com_edu_ndkdemo_HelloNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_ndkdemo_HelloNdk
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
//c语言没有class概念,只有file和function
JNIEXPORT jstring JNICALL Java_com_edu_ndkdemo_HelloNdk_sayHello
        (JNIEnv *env, jobject thiz){
    return (*env)->NewStringUTF(env,"Hello,Ndk...");
}

#ifdef __cplusplus
}
#endif
#endif
